#!/bin/bash

# Activate virtual environment
source $OPENSHIFT_DATA_DIR/myvirtualenv/bin/activate

# Make sure packages in requirements.txt are installed
pip install -r $OPENSHIFT_REPO_DIR/requirements.txt
