#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

source $OPENSHIFT_DATA_DIR/bin/venv/bin/activate
cd $OPENSHIFT_REPO_DIR
python $OPENSHIFT_REPO_DIR/wsgi.py &

